
/**
 * 埃罗西卡大陆联赛训练师数据库
 * 六大地区：伊缇、异提、拜尼、罗娜、罗兰、巴卡
 * 每个地区设有夏季联赛和冬季联赛，每个联赛19名AI选手（加上玩家共20人）
 */
const LEAGUE_TRAINERS_DATA = {
  "version": "2.0",
  "description": "埃罗西卡大陆联赛训练师数据库 - 六大地区夏季/冬季联赛",
  "notes": "每个地区有夏季联赛和冬季联赛两个固定选手池，每个联赛19名AI选手",
  "regions": {
    "伊缇": {
      "夏季联赛": [
        {"id": "yiti_summer_01", "name": "亚历山大", "strength": 95},
        {"id": "yiti_summer_02", "name": "艾米莉", "strength": 92},
        {"id": "yiti_summer_03", "name": "本杰明", "strength": 90},
        {"id": "yiti_summer_04", "name": "夏洛特", "strength": 88},
        {"id": "yiti_summer_05", "name": "丹尼尔", "strength": 86},
        {"id": "yiti_summer_06", "name": "伊莎贝拉", "strength": 84},
        {"id": "yiti_summer_07", "name": "詹姆斯", "strength": 82},
        {"id": "yiti_summer_08", "name": "奥利维亚", "strength": 80},
        {"id": "yiti_summer_09", "name": "威廉", "strength": 78},
        {"id": "yiti_summer_10", "name": "索菲亚", "strength": 76},
        {"id": "yiti_summer_11", "name": "迈克尔", "strength": 74},
        {"id": "yiti_summer_12", "name": "艾玛", "strength": 72},
        {"id": "yiti_summer_13", "name": "大卫", "strength": 70},
        {"id": "yiti_summer_14", "name": "米娅", "strength": 68},
        {"id": "yiti_summer_15", "name": "约瑟夫", "strength": 66},
        {"id": "yiti_summer_16", "name": "艾娃", "strength": 64},
        {"id": "yiti_summer_17", "name": "托马斯", "strength": 62},
        {"id": "yiti_summer_18", "name": "佐伊", "strength": 60},
        {"id": "yiti_summer_19", "name": "罗伯特", "strength": 58}
      ],
      "冬季联赛": [
        {"id": "yiti_winter_01", "name": "查理", "strength": 75},
        {"id": "yiti_winter_02", "name": "格蕾丝", "strength": 73},
        {"id": "yiti_winter_03", "name": "马修", "strength": 71},
        {"id": "yiti_winter_04", "name": "莉莉", "strength": 69},
        {"id": "yiti_winter_05", "name": "安德鲁", "strength": 67},
        {"id": "yiti_winter_06", "name": "克洛伊", "strength": 65},
        {"id": "yiti_winter_07", "name": "克里斯托弗", "strength": 63},
        {"id": "yiti_winter_08", "name": "阿比盖尔", "strength": 61},
        {"id": "yiti_winter_09", "name": "约书亚", "strength": 59},
        {"id": "yiti_winter_10", "name": "汉娜", "strength": 57},
        {"id": "yiti_winter_11", "name": "瑞安", "strength": 55},
        {"id": "yiti_winter_12", "name": "娜塔莉", "strength": 53},
        {"id": "yiti_winter_13", "name": "杰克", "strength": 51},
        {"id": "yiti_winter_14", "name": "萨曼莎", "strength": 49},
        {"id": "yiti_winter_15", "name": "伊森", "strength": 47},
        {"id": "yiti_winter_16", "name": "佩奇", "strength": 45},
        {"id": "yiti_winter_17", "name": "诺亚", "strength": 43},
        {"id": "yiti_winter_18", "name": "露西", "strength": 41},
        {"id": "yiti_winter_19", "name": "利亚姆", "strength": 39}
      ]
    },
    "异提": {
      "夏季联赛": [
        {"id": "yiti2_summer_01", "name": "天佑", "strength": 95},
        {"id": "yiti2_summer_02", "name": "紫萱", "strength": 92},
        {"id": "yiti2_summer_03", "name": "浩然", "strength": 90},
        {"id": "yiti2_summer_04", "name": "诗涵", "strength": 88},
        {"id": "yiti2_summer_05", "name": "子轩", "strength": 86},
        {"id": "yiti2_summer_06", "name": "欣怡", "strength": 84},
        {"id": "yiti2_summer_07", "name": "宇航", "strength": 82},
        {"id": "yiti2_summer_08", "name": "梓涵", "strength": 80},
        {"id": "yiti2_summer_09", "name": "博文", "strength": 78},
        {"id": "yiti2_summer_10", "name": "雨桐", "strength": 76},
        {"id": "yiti2_summer_11", "name": "明轩", "strength": 74},
        {"id": "yiti2_summer_12", "name": "语嫣", "strength": 72},
        {"id": "yiti2_summer_13", "name": "泽宇", "strength": 70},
        {"id": "yiti2_summer_14", "name": "思琪", "strength": 68},
        {"id": "yiti2_summer_15", "name": "瀚海", "strength": 66},
        {"id": "yiti2_summer_16", "name": "若曦", "strength": 64},
        {"id": "yiti2_summer_17", "name": "俊熙", "strength": 62},
        {"id": "yiti2_summer_18", "name": "婉清", "strength": 60},
        {"id": "yiti2_summer_19", "name": "星辰", "strength": 58}
      ],
      "冬季联赛": [
        {"id": "yiti2_winter_01", "name": "逸风", "strength": 75},
        {"id": "yiti2_winter_02", "name": "凌薇", "strength": 73},
        {"id": "yiti2_winter_03", "name": "云飞", "strength": 71},
        {"id": "yiti2_winter_04", "name": "沐晴", "strength": 69},
        {"id": "yiti2_winter_05", "name": "景行", "strength": 67},
        {"id": "yiti2_winter_06", "name": "芷若", "strength": 65},
        {"id": "yiti2_winter_07", "name": "鸿远", "strength": 63},
        {"id": "yiti2_winter_08", "name": "清荷", "strength": 61},
        {"id": "yiti2_winter_09", "name": "旭阳", "strength": 59},
        {"id": "yiti2_winter_10", "name": "素锦", "strength": 57},
        {"id": "yiti2_winter_11", "name": "承志", "strength": 55},
        {"id": "yiti2_winter_12", "name": "映雪", "strength": 53},
        {"id": "yiti2_winter_13", "name": "弘毅", "strength": 51},
        {"id": "yiti2_winter_14", "name": "晓月", "strength": 49},
        {"id": "yiti2_winter_15", "name": "文彬", "strength": 47},
        {"id": "yiti2_winter_16", "name": "碧琳", "strength": 45},
        {"id": "yiti2_winter_17", "name": "嘉诚", "strength": 43},
        {"id": "yiti2_winter_18", "name": "琉璃", "strength": 41},
        {"id": "yiti2_winter_19", "name": "铭哲", "strength": 39}
      ]
    },
    "拜尼": {
      "夏季联赛": [
        {"id": "baini_summer_01", "name": "马克西米利安", "strength": 95},
        {"id": "baini_summer_02", "name": "索菲", "strength": 92},
        {"id": "baini_summer_03", "name": "卢卡斯", "strength": 90},
        {"id": "baini_summer_04", "name": "艾玛", "strength": 88},
        {"id": "baini_summer_05", "name": "菲利克斯", "strength": 86},
        {"id": "baini_summer_06", "name": "汉娜", "strength": 84},
        {"id": "baini_summer_07", "name": "保罗", "strength": 82},
        {"id": "baini_summer_08", "name": "莱娜", "strength": 80},
        {"id": "baini_summer_09", "name": "埃尔文", "strength": 78},
        {"id": "baini_summer_10", "name": "米拉", "strength": 76},
        {"id": "baini_summer_11", "name": "弗里茨", "strength": 74},
        {"id": "baini_summer_12", "name": "克拉拉", "strength": 72},
        {"id": "baini_summer_13", "name": "赫尔曼", "strength": 70},
        {"id": "baini_summer_14", "name": "安娜", "strength": 68},
        {"id": "baini_summer_15", "name": "奥托", "strength": 66},
        {"id": "baini_summer_16", "name": "伊丽莎白", "strength": 64},
        {"id": "baini_summer_17", "name": "沃尔夫冈", "strength": 62},
        {"id": "baini_summer_18", "name": "玛丽亚", "strength": 60},
        {"id": "baini_summer_19", "name": "弗朗茨", "strength": 58}
      ],
      "冬季联赛": [
        {"id": "baini_winter_01", "name": "托比亚斯", "strength": 75},
        {"id": "baini_winter_02", "name": "夏洛蒂", "strength": 73},
        {"id": "baini_winter_03", "name": "约纳斯", "strength": 71},
        {"id": "baini_winter_04", "name": "劳拉", "strength": 69},
        {"id": "baini_winter_05", "name": "尼古拉斯", "strength": 67},
        {"id": "baini_winter_06", "name": "莉娅", "strength": 65},
        {"id": "baini_winter_07", "name": "莫里茨", "strength": 63},
        {"id": "baini_winter_08", "name": "凯瑟琳", "strength": 61},
        {"id": "baini_winter_09", "name": "塞巴斯蒂安", "strength": 59},
        {"id": "baini_winter_10", "name": "佐伊", "strength": 57},
        {"id": "baini_winter_11", "name": "亚历山大", "strength": 55},
        {"id": "baini_winter_12", "name": "艾米莉", "strength": 53},
        {"id": "baini_winter_13", "name": "朱利安", "strength": 51},
        {"id": "baini_winter_14", "name": "克劳迪娅", "strength": 49},
        {"id": "baini_winter_15", "name": "达维德", "strength": 47},
        {"id": "baini_winter_16", "name": "弗兰齐斯卡", "strength": 45},
        {"id": "baini_winter_17", "name": "格奥尔格", "strength": 43},
        {"id": "baini_winter_18", "name": "英格丽德", "strength": 41},
        {"id": "baini_winter_19", "name": "汉斯", "strength": 39}
      ]
    },
    "罗娜": {
      "夏季联赛": [
        {"id": "luona_summer_01", "name": "春树", "strength": 95},
        {"id": "luona_summer_02", "name": "美咲", "strength": 92},
        {"id": "luona_summer_03", "name": "大辅", "strength": 90},
        {"id": "luona_summer_04", "name": "结衣", "strength": 88},
        {"id": "luona_summer_05", "name": "健太", "strength": 86},
        {"id": "luona_summer_06", "name": "爱美", "strength": 84},
        {"id": "luona_summer_07", "name": "拓海", "strength": 82},
        {"id": "luona_summer_08", "name": "莉奈", "strength": 80},
        {"id": "luona_summer_09", "name": "翔太", "strength": 78},
        {"id": "luona_summer_10", "name": "纱绫", "strength": 76},
        {"id": "luona_summer_11", "name": "隼人", "strength": 74},
        {"id": "luona_summer_12", "name": "明日香", "strength": 72},
        {"id": "luona_summer_13", "name": "龙一", "strength": 70},
        {"id": "luona_summer_14", "name": "桃子", "strength": 68},
        {"id": "luona_summer_15", "name": "凉介", "strength": 66},
        {"id": "luona_summer_16", "name": "美羽", "strength": 64},
        {"id": "luona_summer_17", "name": "雄大", "strength": 62},
        {"id": "luona_summer_18", "name": "千夏", "strength": 60},
        {"id": "luona_summer_19", "name": "优太", "strength": 58}
      ],
      "冬季联赛": [
        {"id": "luona_winter_01", "name": "悠斗", "strength": 75},
        {"id": "luona_winter_02", "name": "七海", "strength": 73},
        {"id": "luona_winter_03", "name": "陆", "strength": 71},
        {"id": "luona_winter_04", "name": "葵", "strength": 69},
        {"id": "luona_winter_05", "name": "晴人", "strength": 67},
        {"id": "luona_winter_06", "name": "心春", "strength": 65},
        {"id": "luona_winter_07", "name": "大智", "strength": 63},
        {"id": "luona_winter_08", "name": "遥", "strength": 61},
        {"id": "luona_winter_09", "name": "诚", "strength": 59},
        {"id": "luona_winter_10", "name": "枫", "strength": 57},
        {"id": "luona_winter_11", "name": "翼", "strength": 55},
        {"id": "luona_winter_12", "name": "瞳", "strength": 53},
        {"id": "luona_winter_13", "name": "航", "strength": 51},
        {"id": "luona_winter_14", "name": "梓", "strength": 49},
        {"id": "luona_winter_15", "name": "树", "strength": 47},
        {"id": "luona_winter_16", "name": "凛", "strength": 45},
        {"id": "luona_winter_17", "name": "岬", "strength": 43},
        {"id": "luona_winter_18", "name": "澪", "strength": 41},
        {"id": "luona_winter_19", "name": "陽", "strength": 39}
      ]
    },
    "罗兰": {
      "夏季联赛": [
        {"id": "luolan_summer_01", "name": "敏俊", "strength": 95},
        {"id": "luolan_summer_02", "name": "智恩", "strength": 92},
        {"id": "luolan_summer_03", "name": "俊浩", "strength": 90},
        {"id": "luolan_summer_04", "name": "秀智", "strength": 88},
        {"id": "luolan_summer_05", "name": "泰亨", "strength": 86},
        {"id": "luolan_summer_06", "name": "恩智", "strength": 84},
        {"id": "luolan_summer_07", "name": "宇镇", "strength": 82},
        {"id": "luolan_summer_08", "name": "娜恩", "strength": 80},
        {"id": "luolan_summer_09", "name": "在勋", "strength": 78},
        {"id": "luolan_summer_10", "name": "智秀", "strength": 76},
        {"id": "luolan_summer_11", "name": "灿烈", "strength": 74},
        {"id": "luolan_summer_12", "name": "孝琳", "strength": 72},
        {"id": "luolan_summer_13", "name": "钟国", "strength": 70},
        {"id": "luolan_summer_14", "name": "有真", "strength": 68},
        {"id": "luolan_summer_15", "name": "东海", "strength": 66},
        {"id": "luolan_summer_16", "name": "宝拉", "strength": 64},
        {"id": "luolan_summer_17", "name": "胜贤", "strength": 62},
        {"id": "luolan_summer_18", "name": "善美", "strength": 60},
        {"id": "luolan_summer_19", "name": "亨俊", "strength": 58}
      ],
      "冬季联赛": [
        {"id": "luolan_winter_01", "name": "志龙", "strength": 75},
        {"id": "luolan_winter_02", "name": "多贤", "strength": 73},
        {"id": "luolan_winter_03", "name": "珉豪", "strength": 71},
        {"id": "luolan_winter_04", "name": "彩英", "strength": 69},
        {"id": "luolan_winter_05", "name": "胜利", "strength": 67},
        {"id": "luolan_winter_06", "name": "娜琏", "strength": 65},
        {"id": "luolan_winter_07", "name": "珉赫", "strength": 63},
        {"id": "luolan_winter_08", "name": "志效", "strength": 61},
        {"id": "luolan_winter_09", "name": "泰民", "strength": 59},
        {"id": "luolan_winter_10", "name": "俞利", "strength": 57},
        {"id": "luolan_winter_11", "name": "基范", "strength": 55},
        {"id": "luolan_winter_12", "name": "孝渊", "strength": 53},
        {"id": "luolan_winter_13", "name": "硕珍", "strength": 51},
        {"id": "luolan_winter_14", "name": "润娥", "strength": 49},
        {"id": "luolan_winter_15", "name": "南俊", "strength": 47},
        {"id": "luolan_winter_16", "name": "泰妍", "strength": 45},
        {"id": "luolan_winter_17", "name": "珉奎", "strength": 43},
        {"id": "luolan_winter_18", "name": "世正", "strength": 41},
        {"id": "luolan_winter_19", "name": "度延", "strength": 39}
      ]
    },
    "巴卡": {
      "夏季联赛": [
        {"id": "baka_summer_01", "name": "路易", "strength": 95},
        {"id": "baka_summer_02", "name": "艾玛", "strength": 92},
        {"id": "baka_summer_03", "name": "加布里埃尔", "strength": 90},
        {"id": "baka_summer_04", "name": "克洛伊", "strength": 88},
        {"id": "baka_summer_05", "name": "雨果", "strength": 86},
        {"id": "baka_summer_06", "name": "茱莉", "strength": 84},
        {"id": "baka_summer_07", "name": "马克西姆", "strength": 82},
        {"id": "baka_summer_08", "name": "莉娅", "strength": 80},
        {"id": "baka_summer_09", "name": "拉斐尔", "strength": 78},
        {"id": "baka_summer_10", "name": "莎拉", "strength": 76},
        {"id": "baka_summer_11", "name": "亚历山大", "strength": 74},
        {"id": "baka_summer_12", "name": "克拉拉", "strength": 72},
        {"id": "baka_summer_13", "name": "皮埃尔", "strength": 70},
        {"id": "baka_summer_14", "name": "玛德琳", "strength": 68},
        {"id": "baka_summer_15", "name": "朱利安", "strength": 66},
        {"id": "baka_summer_16", "name": "索菲", "strength": 64},
        {"id": "baka_summer_17", "name": "奥利维耶", "strength": 62},
        {"id": "baka_summer_18", "name": "奥雷莉", "strength": 60},
        {"id": "baka_summer_19", "name": "提奥", "strength": 58}
      ],
      "冬季联赛": [
        {"id": "baka_winter_01", "name": "塞巴斯蒂安", "strength": 75},
        {"id": "baka_winter_02", "name": "夏洛特", "strength": 73},
        {"id": "baka_winter_03", "name": "托马", "strength": 71},
        {"id": "baka_winter_04", "name": "爱丽丝", "strength": 69},
        {"id": "baka_winter_05", "name": "尼古拉", "strength": 67},
        {"id": "baka_winter_06", "name": "茉莉", "strength": 65},
        {"id": "baka_winter_07", "name": "弗朗索瓦", "strength": 63},
        {"id": "baka_winter_08", "name": "卡米尔", "strength": 61},
        {"id": "baka_winter_09", "name": "安托万", "strength": 59},
        {"id": "baka_winter_10", "name": "伊内斯", "strength": 57},
        {"id": "baka_winter_11", "name": "雅克", "strength": 55},
        {"id": "baka_winter_12", "name": "艾米莉", "strength": 53},
        {"id": "baka_winter_13", "name": "马修", "strength": 51},
        {"id": "baka_winter_14", "name": "玛丽", "strength": 49},
        {"id": "baka_winter_15", "name": "帕特里克", "strength": 47},
        {"id": "baka_winter_16", "name": "艾莎", "strength": 45},
        {"id": "baka_winter_17", "name": "樊尚", "strength": 43},
        {"id": "baka_winter_18", "name": "薇薇安", "strength": 41},
        {"id": "baka_winter_19", "name": "奥利弗", "strength": 39}
      ]
    }
  }
};
